### ISSUE TITLE
Support for functon metadata/fragment designation, API handling difference maybe?

### ISSUE THREAD

**Issue by bglusman** [alexdesousa/ayesql#41]
Sorry for so many issues!  this is definitely a small feature request/discussion curious for thoughts on, but, I'm seeing that there are 2 classes of queries/functions in AyeSQL, valid queries in their own right, and fragments (often passed in to optional parameters).  I'm wondering if this distinction can/should be promoted to a first class difference somehow, and/or have metadata exposed for it somehow directly from the definition, if some kind of, say `--fragment: true` or some other such feature were supported.

Fragments probably should ONLY be accessible via inclusion into other queries or other fragments, and even if they're allowed to be called directly, it might be nice to know what's intended as a fragment and what's a full valid query with or without parameters... my main motivation here is, for safety, I'm attempting to run an `EXPLAIN` on all the queries to sort of "type check" them against my schema, but I have to manually exclude the fragments which will fail the EXPLAIN since they're not valid queries.  My workaround at the moment is callback in the Queries module called `fragment_functions` but it would be cleaner if fragments were somehow declared as such inline in the .sql I think.  Curious for thoughts/alternatives etc!

**Comment by alexdesousa** [comment]
@bglusman Thanks for the feedback!

When I introduce the fragments a while back, I thought about adding extra checks for the functions, but then I refrained from doing that, because I wanted AyeSQL to be as minimal as possible. AyeSQL doesn't validate SQL (e.g. you can even use Redis querying language). The lexer and parser are very simple. The only present keywords are:

- `-- name:` for setting the name of the function.
- `-- docs:` for adding documentation.
- `:<var>`: For concrete values to be passed.
- `:_<var>`: For fragments.

## My Approach

To avoid running the wrong queries, I basically avoid adding `-- docs:` to the fragment. This translates to the function being public (which is needed), but not visible when auto-completing e.g. `@doc false`.

If the module was compiled and `.beam` files exist, then in IEx:
- The function won't autocomplete when hitting the tab key,
- And using the `h` helper function won't display any docs.

It's not perfect, but it doesn't introduce unnecessary complexity (IMO) to the language.

## Fragment Support

To give you a concrete example, this is an SQL file I would write for a query:

```sql
-- name: get_players
-- docs: Gets all players with the possibility to extend the query.
SELECT *
  FROM atp
  :_where
  :_order_by
  :_limit

-- name: filter_by_hand
WHERE hand = :hand

-- name: ascending
ORDER BY name_last ASC

-- name: descending
ORDER BY name_last DESC

-- name: limit
LIMIT :rows
```

So, if I add the following code to a `.iex.exs`:

<details>
<summary>Expand to see </summary>

```elixir
Mix.install([
  {:duckdbex, "~> 0.3"},
  {:ayesql, "~> 1.1"}
])

################################################################################
# Prepare test data

defmodule Database do
  @url "https://raw.githubusercontent.com/duckdb-in-action/examples/refs/heads/main/ch05/atp/atp_players.csv"

  def open do
    with {:ok, db} <- Duckdbex.open(),
         {:ok, conn} <- Duckdbex.connection(db),
         {:ok, _res} <- Duckdbex.query(conn, "INSTALL httpfs"),
         {:ok, _res} <- Duckdbex.query(conn, "LOAD httpfs"),
         {:ok, _res} <- Duckdbex.query(conn, "CREATE OR REPLACE TABLE atp AS FROM '#{@url}'") do
      {:ok, {db, conn}}
    end
  end
end

################################################################################
# Setup query

defmodule ATP do
  use AyeSQL, runner: AyeSQL.Runner.Duckdbex

  defqueries "./atp.sql"
end

################################################################################
# Run query

{:ok, {_db, conn}} = Database.open()
```
</details>

Then I can run the following in IEx:

```elixir
iex> ATP.get_players!([
  hand: "L",
  rows: 3,
  _where: &ATP.filter_by_hand/2,
  _order_by: &ATP.ascending/2,
  _limit: &ATP.limit/2
], conn: conn)
```
<details>
<summary>Expand to see result</summary>

```elixir
[
  %{
    hand: "L",
    player_id: 110701,
    name_first: "Hashim",
    name_last: "Abdal",
    dob: "19891126",
    ioc: "KUW",
    height: nil,
    wikidata_id: nil
  },
  %{
    hand: "L",
    player_id: 208356,
    name_first: "Anas",
    name_last: "Abdelouahid",
    dob: "20021004",
    ioc: "USA",
    height: nil,
    wikidata_id: nil
  },
  %{
    hand: "L",
    player_id: 137812,
    name_first: "Kabiru",
    name_last: "Abdulmalik",
    dob: "19940726",
    ioc: "NGR",
    height: nil,
    wikidata_id: nil
  }
]
```

</details>

And we can also check the generated SQL with:

```elixir

iex> ATP.get_players!([
  hand: "L",
  rows: 3,
  _where: &ATP.filter_by_hand/2,
  _order_by: &ATP.ascending/2,
  _limit: &ATP.limit/2
], conn: conn, run: false)
```


<details>
<summary>Expand to see result</summary>

```elixir
%AyeSQL.Query{
  statement: "SELECT * FROM atp WHERE hand = $1 ORDER BY name_last ASC LIMIT $2",
  arguments: ["L", 3]
}
```

</details>

## Alternative

If you take my approach of not setting a `-- docs:` for fragments, then you can query the functions with documentation only e.g. let's take `ATP` and query it's documented functions:

> **Note**: For this example, we need to assume:
> -  The module lives in a mix project,
> -  And it has an associated `.beam` files in the `_build` folder.
> This is not the case if you run the example as I presented it in this post.

```elixir
module = ATP
{_, _, _, _, _, _, entities} = Code.fetch_docs(module)

documented_entities = Enum.reject(entities, fn {_, _, _, docs, _} -> docs == :hidden end)

documented_functions =
  Enum.reduce(documented_entities, [], fn
     {{:function, name, arity}, _, _, _, _}, acc -> Keyword.put(acc, name, arity)
     _, acc -> acc
  end)
```

For the module `ATP`, this should give the following list of functions:

```elixir
[
  get_players: 1,
  get_players: 2,
  get_players!: 1,
  get_players!: 2,
  run: 1,
  run: 2,
  run!: 1,
  run!: 2
]
```

## Conclusion

In general, I will reject any changes to the AyeSQL language unless they are bug fixes as I want to keep the language as simple as possible.

Though I hope my answer help you!

**Comment by bglusman** [comment]
Closing this as we seem to have an acceptable workaround...  we COULD consider documenting this in docs and/or adding some helpers to the library to make this more canonical as a pattern?

I wound up with this somewhat awkward helper function FWIW/for anyone stumbling across this in the future:
```
  defp get_documented_functions(module) do
    fns_metadata =
      module |> Code.fetch_docs() |> elem(6)

    fns_metadata
    |> Enum.filter(&is_map(elem(&1, 3)))
    |> Enum.map(&elem(&1, 0))
  end
  ```
which returns (somewhat awkward) 3-tuples of `{:function, function_name, arity}` that I can then work with well enough to only explain those functions SQL.
